_target_: ctd.task_modeling.simulator.neural_simulator.NeuralDataSimulatorGeneral
n_neurons: 50
<<<<<<< HEAD
nonlin_embed: False


=======
embed_dict:
  rect_func: exp
  fr_scaling: 2.0
noise_dict:
  obs_noise: pseudoPoisson
  dispersion: 1.0
>>>>>>> upstream/main
