_target_: ctd.task_modeling.task_env.random_target.RandomTarget
effector:
  _target_: motornet.effector.RigidTendonArm26
  muscle:
    _target_: motornet.muscle.MujocoHillMuscle
max_ep_duration: 3.0
action_noise: 0.005
proprioception_noise: 0.005
proprioception_delay: 0
vision_noise: 0.005
vision_delay: 0

context_input_noise: 0.04
