_target_: ctd.task_modeling.task_env.multitask.MultiTaskWrapper
dataset_name: MultiTask
task_list:
  - DelayPro
  - MemoryPro
  - ReactPro
  - DelayAnti
  - MemoryAnti
  - ReactAnti
  - IntMod1
  - IntMod2
  - ContextIntMod1
  - ContextIntMod2
  - ContextIntMultimodal
  - Match2Sample
  - NonMatch2Sample
  - MatchCatPro
  - MatchCatAnti

n_timesteps: 500
noise: 0.05
dynamic_noise: 0.0
num_targets: 32
bin_size: 20
grouped_sampler: True
latent_l2_wt: 1e-6